#пустой коммит для запуска воркфлоу
version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: vasiluk23/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/app/backend_static/
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: vasiluk23/kittygram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: vasiluk23/kittygram_gateway:latest
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
